version: '3'

services:
  mqqtt_to_el:
    env_file:
      - .env
    depends_on:
      - elasticsearch-local
  elasticsearch-local:
    container_name: elasticsearch-local
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0"
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - "./data:/usr/share/elasticsearch/data"
    - "./config:/usr/share/elasticsearch/config"
